"""Actividad1-inducion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alAloHGHVZYBQK031ufGJjRjDfWWwgz_

1. Qué operadores utiliza Python en los siguientes casos:

<ul style="list-style-type: none;">
  <li>División Modular</li>
  <li>Exponenciación</li>
  <li>División que retorne entero.</li>
      
</ul>
"""

num1 = 2;
num2 = 3;

print(f"El modulo es con el operador %, modulo de {num1} entre {num2} es {num1 % num2}")
print(f"El exponente es con el operador **, exponente de {num1} a la {num2} es {num1 ** num2}")
print(f"La divicion entera es con el operador //, la dicion entera de {num1} entre {num2} es {num1 // num2}")